#!/usr/bin/env python3
"""
Northline Finds — static storefront builder.

Reads:
  ../research/products.json   (product catalog; override with --products)
  assets/js/products.js       (per-product Stripe Payment Links; auto-synced)

Generates:
  index.html                  (hero + category filter + product grid)
  products/<id>.html          (one page per product)
  cart.html                   (checkout page, rendered from catalog.js)
  assets/js/catalog.js        (product data for the JS cart)
  assets/js/products.js       (config preserved + synced with product ids)

Re-run any time products.json changes or Stripe links are added:
  python3 build.py
"""
import argparse
import html
import json
import re
from pathlib import Path

STORE = Path(__file__).resolve().parent
RESEARCH_JSON = STORE.parent / "research" / "products.json"

# ---- easily renameable brand config ----
STORE_NAME = "Northline Finds"
CONTACT_EMAIL = "roman.proposal@gmail.com"
TAGLINE = "Useful finds, honestly priced."
SHIPPING_LINE = "Ships in 7\u201312 business days"

IMG_EXTS = [".jpg", ".jpeg", ".png", ".webp", ".svg"]
PLACEHOLDER = "assets/img/placeholder.svg"


def esc(s):
    return html.escape("" if s is None else str(s), quote=True)


def money(n):
    try:
        return f"${float(n):.2f}"
    except (TypeError, ValueError):
        return "$0.00"


def safe_id(pid):
    s = re.sub(r"[^a-z0-9\-_]", "-", str(pid).lower()).strip("-")
    return s or "product"


def load_products(path):
    data = json.loads(Path(path).read_text(encoding="utf-8"))
    if isinstance(data, dict) and "products" in data:
        data = data["products"]
    products = []
    for p in data:
        p = dict(p)
        p["_safe"] = safe_id(p.get("id", "product"))
        products.append(p)
    return products


def image_for(p):
    for ext in IMG_EXTS:
        f = STORE / "assets" / "img" / (p["_safe"] + ext)
        if f.exists():
            return f"assets/img/{p['_safe']}{ext}"
    return PLACEHOLDER


# ---------- existing stripe links ----------
def load_stripe_links():
    cfg = STORE / "assets" / "js" / "products.js"
    links = {}
    if not cfg.exists():
        return links
    text = cfg.read_text(encoding="utf-8")
    m = re.search(r"stripeLinks\s*:\s*\{", text)
    if not m:
        return links
    depth, start = 0, m.end() - 1
    for i in range(start, len(text)):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                block = text[start:i + 1]
                break
    else:
        return links
    for km in re.finditer(r'"([^"]+)"\s*:\s*"([^"]*)"', block):
        links[km.group(1)] = km.group(2)
    return links


def write_products_js(products, links):
    lines = [
        "/* %s store config." % STORE_NAME,
        " * Paste each product's Stripe Payment Link below, then re-run:  python3 build.py",
        " * (build.py preserves links you've already filled in.)",
        " */",
        "window.STORE_CONFIG = {",
        '  storeName: "%s",' % STORE_NAME,
        '  contactEmail: "%s",' % CONTACT_EMAIL,
        "  stripeLinks: {",
    ]
    for p in products:
        pid = p.get("id", "")
        link = links.get(pid, "")
        lines.append('    "%s": "%s",' % (pid.replace('"', ""), link.replace('"', "")))
    lines += ["  }", "};", ""]
    (STORE / "assets" / "js" / "products.js").write_text("\n".join(lines), encoding="utf-8")


def write_catalog_js(products):
    cat = {}
    for p in products:
        pid = p.get("id", "")
        cat[pid] = {
            "id": pid,
            "name": p.get("name", ""),
            "tagline": p.get("tagline", ""),
            "retail_price": float(p.get("retail_price") or 0),
            "category": p.get("category", ""),
            "image": image_for(p),
        }
    out = "/* generated by build.py — do not edit by hand */\nwindow.CATALOG = " + json.dumps(cat, indent=2) + ";\n"
    (STORE / "assets" / "js" / "catalog.js").write_text(out, encoding="utf-8")


# ---------- shared chrome ----------
def header(active=""):
    return f"""<header class="site-header">
  <div class="container header-inner">
    <a class="brand" href="index.html" aria-label="{esc(STORE_NAME)} home">
      <span class="brand-mark" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none"><path d="M12 2 L14.5 9.5 L22 12 L14.5 14.5 L12 22 L9.5 14.5 L2 12 L9.5 9.5 Z" fill="#fff"/></svg></span>
      {esc(STORE_NAME)}
    </a>
    <nav class="nav-links" aria-label="Primary">
      <a href="index.html">Shop</a>
      <a href="about.html">About</a>
      <a href="faq.html">FAQ</a>
      <a href="contact.html">Contact</a>
    </nav>
    <div class="header-actions">
      <button class="cart-btn" data-open-cart aria-label="Open cart">
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="9" cy="21" r="1.5"/><circle cx="19" cy="21" r="1.5"/><path d="M2 3h3l2.6 12.5a2 2 0 0 0 2 1.5h8.7a2 2 0 0 0 2-1.6L22 7H6"/></svg>
        Cart <span class="cart-count" data-cart-count>0</span>
      </button>
    </div>
  </div>
</header>"""


DRAWER = """<div class="drawer-overlay" id="drawer-overlay"></div>
<aside class="drawer" id="cart-drawer" aria-label="Shopping cart">
  <div class="drawer-head"><h2>Your cart</h2><button class="drawer-close" data-close-cart aria-label="Close cart">✕</button></div>
  <div class="drawer-items" id="drawer-items"></div>
  <div class="drawer-foot" id="drawer-foot">
    <div class="drawer-total"><span>Subtotal</span><span id="drawer-total">$0.00</span></div>
    <a class="btn btn-primary btn-block" href="cart.html">Review &amp; checkout</a>
    <button class="btn btn-outline btn-block" data-close-cart>Keep shopping</button>
  </div>
</aside>
<div class="toast" id="toast" role="status"></div>"""


def footer():
    return f"""<footer class="site-footer">
  <div class="container">
    <div class="footer-grid">
      <div>
        <div class="footer-brand">{esc(STORE_NAME)}</div>
        <p>{esc(TAGLINE)} A small online shop curating trending products we&apos;d buy ourselves. Every order is backed by 30-day returns and real human support.</p>
        <p class="small">Questions? <a href="mailto:{esc(CONTACT_EMAIL)}" style="color:#fff">{esc(CONTACT_EMAIL)}</a></p>
      </div>
      <div>
        <div class="footer-brand" style="font-size:.95rem">Shop</div>
        <ul class="footer-links">
          <li><a href="index.html">All products</a></li>
          <li><a href="cart.html">Cart &amp; checkout</a></li>
          <li><a href="shipping.html">Shipping info</a></li>
        </ul>
      </div>
      <div>
        <div class="footer-brand" style="font-size:.95rem">Help</div>
        <ul class="footer-links">
          <li><a href="about.html">About us</a></li>
          <li><a href="faq.html">FAQ</a></li>
          <li><a href="refunds.html">Returns &amp; refunds</a></li>
          <li><a href="contact.html">Contact</a></li>
        </ul>
      </div>
    </div>
    <div class="footer-bottom">
      <span>© 2026 {esc(STORE_NAME)}. All rights reserved.</span>
      <span>Secure checkout powered by Stripe.</span>
    </div>
  </div>
</footer>"""


def page(title, desc, body, extra_head=""):
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{esc(title)} — {esc(STORE_NAME)}</title>
<meta name="description" content="{esc(desc)}">
<link rel="icon" href="assets/img/favicon.svg" type="image/svg+xml">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;750;800&display=swap" rel="stylesheet">
<link rel="stylesheet" href="assets/css/style.css">
{extra_head}</head>
<body>
{header()}
{body}
{footer()}
{DRAWER}
<script src="assets/js/products.js"></script>
<script src="assets/js/catalog.js"></script>
<script src="assets/js/app.js"></script>
</body>
</html>
"""


def page_nested(title, desc, body):
    """Same as page() but for files inside products/ (paths go one level up)."""
    html_out = page(title, desc, body)
    return (html_out
            .replace('href="index.html"', 'href="../index.html"')
            .replace('href="about.html"', 'href="../about.html"')
            .replace('href="faq.html"', 'href="../faq.html"')
            .replace('href="contact.html"', 'href="../contact.html"')
            .replace('href="cart.html"', 'href="../cart.html"')
            .replace('href="shipping.html"', 'href="../shipping.html"')
            .replace('href="refunds.html"', 'href="../refunds.html"')
            .replace('href="assets/', 'href="../assets/')
            .replace('src="assets/', 'src="../assets/')
            .replace('src="assets/img/favicon.svg"', 'src="../assets/img/favicon.svg"'))


TRUST_ITEMS = [
    ("M12 2l2.4 4.9 5.4.8-3.9 3.8.9 5.4L12 14.4 7.2 16.9l.9-5.4L4.2 7.7l5.4-.8z",
     "Secure checkout via Stripe"),
    ("M3 12a9 9 0 1 0 3-6.7M3 4v5h5",
     "30-day easy returns"),
    ("M1 8h13v9H1zM14 11h4l3 3v3h-7zM5.5 20a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3zm12 0a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3z",
     SHIPPING_LINE),
]


def trust_row():
    items = []
    for path, label in TRUST_ITEMS:
        items.append(
            f'<li><svg viewBox="0 0 24 24" fill="none" stroke="#06b6d4" stroke-width="2">'
            f'<path d="{path}"/></svg>{esc(label)}</li>')
    return '<ul class="trust-row">' + "".join(items) + "</ul>"


def card_html(p):
    pid = esc(p.get("id", ""))
    return f"""<a class="card" href="products/{p['_safe']}.html" data-category="{esc(p.get('category',''))}">
  <div class="card-media"><img src="{esc(image_for(p))}" alt="{esc(p.get('name',''))}" loading="lazy"></div>
  <div class="card-body">
    <div class="card-cat">{esc(p.get('category',''))}</div>
    <h3 class="card-title">{esc(p.get('name',''))}</h3>
    <p class="card-tag">{esc(p.get('tagline',''))}</p>
    <div class="card-row"><span class="price">{money(p.get('retail_price'))}</span>
    <button class="add-btn" data-add="{pid}" aria-label="Add {pid} to cart">Add +</button></div>
  </div>
</a>"""


def build_index(products, links):
    cats = sorted({p.get("category", "Misc") for p in products if p.get("category")})
    pills = ['<button class="pill active" data-cat="all">All</button>'] + [
        f'<button class="pill" data-cat="{esc(c)}">{esc(c)}</button>' for c in cats]
    cards = "\n".join(card_html(p) for p in products)
    body = f"""<section class="hero">
  <div class="container">
    <span class="hero-eyebrow">New finds added regularly</span>
    <h1>Everyday products worth your money.</h1>
    <p class="lead">{esc(STORE_NAME)} is a small curated shop. We track down trending, genuinely useful products, test the listings ourselves, and sell them at honest prices — no inflated &quot;was $199&quot; games.</p>
    <div class="hero-cta">
      <a class="btn btn-primary" href="#shop">Shop trending now</a>
      <a class="btn btn-outline" href="about.html">How we choose products</a>
    </div>
    {trust_row()}
  </div>
</section>
<div class="filter-bar" id="shop">
  <div class="container"><div class="pills" role="tablist" aria-label="Filter by category">
    {''.join(pills)}
  </div></div>
</div>
<section class="section">
  <div class="container">
    <div class="grid">
{cards}
    </div>
  </div>
</section>
<section class="info-strip">
  <div class="container">
    <h2>Shop with confidence</h2>
    <div class="info-grid">
      <div class="info-card"><h3>Honest shipping times</h3><p>Our products ship directly from our supply partners in {esc(SHIPPING_LINE).lower()}. You&apos;ll get tracking the moment your order leaves the warehouse — no surprises.</p></div>
      <div class="info-card"><h3>30-day returns</h3><p>Changed your mind? Return any unused item within 30 days for a full refund. We cover the return label on damaged or wrong items.</p></div>
      <div class="info-card"><h3>Real human support</h3><p>Questions before or after you buy? Email us at {esc(CONTACT_EMAIL)} — a real person replies, usually within a day.</p></div>
    </div>
  </div>
</section>"""
    return page(f"Trending Products, Honestly Priced",
                f"{STORE_NAME}: a curated shop of trending, useful products at honest prices. {SHIPPING_LINE}, 30-day returns.",
                body)


def buy_button(p, links):
    pid = p.get("id", "")
    link = links.get(pid, "")
    price = money(p.get("retail_price"))
    if link:
        return (f'<a class="btn btn-primary btn-block" id="buy-now" data-id="{esc(pid)}" '
                f'href="{esc(link)}" target="_blank" rel="noopener">Buy now — {price}</a>')
    mailto = f"mailto:{CONTACT_EMAIL}?subject=" + esc(f"Order inquiry: {p.get('name','')}")
    return (f'<a class="btn btn-primary btn-block" id="buy-now" data-id="{esc(pid)}" '
            f'href="{mailto}">Email us to order</a>'
            f'<p class="small muted center" style="margin:0">Online checkout for this item opens soon — email us and we&apos;ll take care of your order.</p>')


def build_product_page(p, products, links):
    pid = p.get("id", "")
    related = [q for q in products if q.get("id") != pid and q.get("category") == p.get("category")][:4]
    if len(related) < 4:
        related += [q for q in products if q.get("id") != pid and q not in related][:4 - len(related)]
    rel_cards = "\n".join(card_html(q) for q in related)
    why = p.get("why_trending") or ""
    body = f"""<div class="container">
  <nav class="breadcrumb" aria-label="Breadcrumb"><a href="../index.html">Home</a> &rsaquo; <a href="../index.html#shop">{esc(p.get('category',''))}</a> &rsaquo; {esc(p.get('name',''))}</nav>
  <div class="product-layout">
    <div class="product-gallery"><img src="{esc(image_for(p))}" alt="{esc(p.get('name',''))}"></div>
    <div class="product-info">
      <div class="card-cat">{esc(p.get('category',''))}</div>
      <h1>{esc(p.get('name',''))}</h1>
      <p class="product-tagline">{esc(p.get('tagline',''))}</p>
      <div class="price-lg">{money(p.get('retail_price'))}</div>
      <div class="ship-note"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4"><path d="M20 6L9 17l-5-5"/></svg>{esc(SHIPPING_LINE)} · Free shipping · 30-day returns</div>
      <div class="buy-box">
        <div class="qty-row">
          <span class="small muted"><strong>Quantity</strong></span>
          <div class="qty"><button data-qty="-1" aria-label="Decrease quantity">−</button><span id="qty-val">1</span><button data-qty="1" aria-label="Increase quantity">+</button></div>
        </div>
        <button class="btn btn-accent btn-block" id="add-to-cart" data-id="{esc(pid)}">Add to cart</button>
        {buy_button(p, links)}
        <div class="secure-line"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="4" y="10" width="16" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/></svg>Secure checkout powered by Stripe</div>
      </div>
      {"<div class='why-box'><h3>Why it&apos;s trending</h3><p>" + esc(why) + "</p></div>" if why else ""}
      <div class="desc-block">
        <h2>About this product</h2>
        <p>{esc(p.get('description',''))}</p>
      </div>
      <div class="accordion">
        <details open><summary>Shipping &amp; delivery</summary><div class="acc-body">Orders ship from our supply partners within 1–2 business days and arrive in {esc(SHIPPING_LINE).lower()}. Shipping is free, and you&apos;ll receive a tracking number by email as soon as your order leaves the warehouse. See our <a href="../shipping.html">shipping page</a> for details.</div></details>
        <details><summary>Returns</summary><div class="acc-body">Not happy? Return any unused item within 30 days for a full refund — no questions asked, no restocking fees. Full details on our <a href="../refunds.html">returns page</a>.</div></details>
        <details><summary>Is this legit?</summary><div class="acc-body">Yes. {esc(STORE_NAME)} is a real small business. We only list products from suppliers we&apos;ve vetted, we answer every email at {esc(CONTACT_EMAIL)}, and every payment is processed securely by Stripe — we never see or store your card details.</div></details>
      </div>
    </div>
  </div>
  <section class="section related">
    <h2>You may also like</h2>
    <div class="grid">
{rel_cards}
    </div>
  </section>
</div>"""
    return page_nested(p.get("name", "Product"), p.get("tagline", "") or p.get("name", ""), body)


def build_cart():
    body = """<div class="page-hero"><div class="container">
  <h1>Your cart</h1>
  <p class="muted" style="max-width:36em">Review your items and check out securely. Each item checks out through Stripe — we never see or store your payment details.</p>
</div></div>
<section class="section"><div class="container" style="max-width:760px">
  <div id="cart-empty" class="hidden"><div class="drawer-empty">
    <p><strong>Your cart is empty.</strong></p>
    <p class="small">Head back to the shop and grab something useful.</p>
    <a class="btn btn-primary" href="index.html" style="margin-top:12px">Browse products</a>
  </div></div>
  <div id="cart-list"></div>
  <div id="cart-page-lines"></div>
  <div class="stripe-note"><strong>How checkout works:</strong> press &quot;Pay securely&quot; on an item and you&apos;ll go to Stripe&apos;s secure payment page to complete your purchase. You&apos;ll get an email receipt plus tracking as soon as your order ships.</div>
  <p class="small muted center" style="margin-top:24px"><a href="shipping.html">Shipping info</a> · <a href="refunds.html">Returns &amp; refunds</a> · <a href="faq.html">FAQ</a></p>
</div></section>"""
    # renderCartPage() in app.js fills #cart-page-lines; #cart-list kept for structure
    return page("Your Cart", "Review your cart and check out securely with Stripe.", body)


# (title, meta description) for each hand-editable page in content/
CONTENT_PAGES = [
    ("about.html", "About Us", "How Northline Finds chooses products, and what we stand for."),
    ("faq.html", "FAQ", "Answers about shipping, returns, payments, and how Northline Finds works."),
    ("shipping.html", "Shipping Info", "How long shipping takes, tracking, and shipping costs at Northline Finds."),
    ("refunds.html", "Returns & Refunds", "Our 30-day return policy: full refunds, no questions asked."),
    ("contact.html", "Contact Us", "Get in touch with Northline Finds — real human support."),
]


def build_content_pages():
    content_dir = STORE / "content"
    built = []
    for slug, title, desc in CONTENT_PAGES:
        frag = content_dir / (slug[:-5] + ".html")
        if not frag.exists():
            print(f"  (skip {slug}: content/{frag.name} not found)")
            continue
        (STORE / slug).write_text(page(title, desc, frag.read_text(encoding="utf-8")), encoding="utf-8")
        built.append(slug)
    return built


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--products", default=str(RESEARCH_JSON))
    args = ap.parse_args()

    products = load_products(args.products)
    if not products:
        raise SystemExit("No products found in " + args.products)
    links = load_stripe_links()

    write_products_js(products, links)
    write_catalog_js(products)

    (STORE / "index.html").write_text(build_index(products, links), encoding="utf-8")
    prod_dir = STORE / "products"
    prod_dir.mkdir(exist_ok=True)
    wanted = set()
    for p in products:
        fname = p["_safe"] + ".html"
        wanted.add(fname)
        (prod_dir / fname).write_text(build_product_page(p, products, links), encoding="utf-8")
    for stale in prod_dir.glob("*.html"):
        if stale.name not in wanted:
            stale.unlink()
            print(f"  removed stale page: products/{stale.name}")
    (STORE / "cart.html").write_text(build_cart(), encoding="utf-8")
    content_built = build_content_pages()

    missing_img = [p.get("id") for p in products if image_for(p) == PLACEHOLDER]
    missing_links = [p.get("id") for p in products if not links.get(p.get("id"), "")]
    print(f"Built {len(products)} products -> index.html, cart.html, {len(products)} product pages, {len(content_built)} content pages.")
    print(f"Images: {len(products) - len(missing_img)}/{len(products)} have photos; placeholder used for: {missing_img or 'none'}")
    print(f"Stripe links: {len(products) - len(missing_links)}/{len(products)} set; missing for: {missing_links or 'none'}")


if __name__ == "__main__":
    main()
